// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20210602184946_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Travel.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Reviews")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceId = 1,
                            Country = "Thailand",
                            Name = "Phi Phi Islands",
                            Reviews = "Woolly Mammoth"
                        },
                        new
                        {
                            PlaceId = 2,
                            Country = "United States",
                            Name = "Yellow Stones",
                            Reviews = "Dinosaur"
                        },
                        new
                        {
                            PlaceId = 3,
                            Country = "Brazil",
                            Name = "Rio de Janeiro",
                            Reviews = "Dinosaur"
                        },
                        new
                        {
                            PlaceId = 4,
                            Country = "England",
                            Name = "London",
                            Reviews = "Shark"
                        },
                        new
                        {
                            PlaceId = 5,
                            Country = "France",
                            Name = "Paris",
                            Reviews = "Dinosaur"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
